version: '3'
services:
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/svr/www
    ports:
      - "3000:3000"
    depends_on:
      - db
