default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: giglist_development

test:
  <<: *default
  database: giglist_test

production: 
  <<: *default
  database: giglist
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
